language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pytest


jobs:
  include:
    - stage:
      language: python
      python: 3.6
      script: echo "setting up travis to enable local runs"
